### ISSUE TITLE
テーブルのハードコードを避ける

### ISSUE THREAD

**Issue by omasanori** [tokuhirom/akaza#155]
一方で、現状でもテーブルを定義するRustコードを書き換えてリビルドすればテーブルの変更は可能で、hackableなかな漢字変換エンジンとしてはそれで充分という考え方もある。

他方で、将来Akazaが各ディストリビューションのパッケージとして配布されるようになると、自分でAkazaをビルドしない利用者が発生する。これはAkazaにとって悪いことではないが、そのような利用者はハードコードされたテーブルを変更できない。テーブルのハードコードを避けて外部ファイルに追い出すか、設定でテーブルの追記や置き換えができるとこのような利用者にとって便利。

**Comment by tokuhirom** [comment]
今ハードコードされてるのは、ローマ字変換テーブルとibus-akazaのキーバインディングですね。

**Comment by tokuhirom** [comment]
キーバインディングについては config.yml にかけるようになっていると良さそうだな、と思っています。
ローマ字変換テーブルも同様かな。

という感じなので、ベースのテーブル自体はハードコードで、yml で上書きできるみたいな感じがよいのかな、と。

**Comment by tokuhirom** [comment]
キーマップについては https://github.com/tokuhirom/akaza/blob/master/ibus-akaza/src/keymap.rs に書いてあって、command を呼ぶような形にしてあるので、emacs のようにキーマップを変更できるように変えられるように設計してあります。

**Comment by tokuhirom** [comment]
言ってるそばから、かな入力のキーマップをハードコードしたけど、これはたぶんハードコードでいいはず! JIS 規格だからいじりたい人いないはず。

**Comment by tokuhirom** [comment]
libkkc のテーブル、実は GPL ではないようなので、これをそのまま再利用させていただくのが良いかも。

**Comment by omasanori** [comment]
> 言ってるそばから、かな入力のキーマップをハードコードしたけど、これはたぶんハードコードでいいはず! JIS 規格だからいじりたい人いないはず。

非JIS配列でかな入力したい人、とか？

**Comment by tokuhirom** [comment]
そういう需要があるのかどうかさっぱりわかってないですw

**Comment by tokuhirom** [comment]
仮名入力、ふつうにマップだけでいけそうなので、libkkc の json をうまいこと読めるようにするという方向でやってみようかなと

**Comment by tokuhirom** [comment]
キーマップのATOK風、とかもこれで一通り賄えるとおもうので。

**Comment by tokuhirom** [comment]
ローマ字入力から先に対応するのが良さそう。キャリーオーバーの概念がいまないけど、そこさえ出来ればわりとうまくいきそう。

**Comment by tokuhirom** [comment]
kkc のものをそのまま持ってくるのはいろいろ面倒そうだったので独自フォーマットで #174 を実装。
コメントを書きたいので YAML とする。

**Comment by tokuhirom** [comment]
間違えてクローズしていました

**Comment by tokuhirom** [comment]
キーバインディングとローマ字テーブルの両方が外部ファイル化された!ので一旦クローズで良さそうです!
(今後もなにか外部ファイル化したくなるものあるのかな?)
