### ISSUE TITLE
モデルファイルの配布

### ISSUE THREAD

**Issue by tokuhirom** [tokuhirom/akaza#75]
github releases で配布できるようにしたい

**Comment by tokuhirom** [comment]
github actions でのモデル生成が 6時間では終わらない傾向。

**Comment by tokuhirom** [comment]
#70 が出来たら、0.1.0 をリリースして良さそう。

**Comment by tokuhirom** [comment]
初めて、リリースに成功したけどなんか失敗していて一個ずつ別のファイルが生成されている！
なんてっこった。

**Comment by omasanori** [comment]
そういう仕様みたいですね。（[参考1](https://github.com/fnkr/github-action-ghr/blob/v1/README.md?plain=1#L15)、[参考2](https://github.com/fnkr/github-action-ghr/blob/v1/ghr-wrapper#L7)、[参考3](https://github.com/fnkr/github-action-ghr/blob/v1/ghr-compress#L44-L51)）

私が似たような目的で書いたアクションを参考に貼っておきます。 https://github.com/mawww/kakoune/blob/master/.github/workflows/build-releases-linux.yaml#L25-L29

**Comment by tokuhirom** [comment]
ありがとうございます！
https://github.com/tokuhirom/akaza/commit/04af67ecc70076a49082770ae1d6b314e36dd620 これでいけるかな〜

**Comment by tokuhirom** [comment]
一旦、配布できるようになったのでクローズ
